### ISSUE TITLE
Rules config

### ISSUE THREAD

**Issue by DragorWW** [DragorWW/phplint#7]
## TODO
- [x] load config form `.phplint.yaml`
- [ ] default config from rule
- [ ] schema in rule for validate config

## Question
- usage `TreeBuilder` from `Simfony/Config`
```php
$rootNode
    ->children()
        ->enumNode('gender')
            ->values(array('male', 'female'))
        ->end()
    ->end()
;
```
- or usage scheme validator
```js
// example from eslint
module.exports = {
    meta: {
        schema: [
            {
                "enum": ["always", "never"]
            },
            {
                "type": "object",
                "properties": {
                    "exceptRange": {
                        "type": "boolean"
                    }
                },
                "additionalProperties": false
            }
        ];
    },
};
```

## API
```yaml
rules:
  eqeqeq: off
  curly: error
  quotes:
    - error
    - double
```

```php
<?php
class MyRule extend Rule
{
  public function getSchema()
  {
    return []; // json scheme
  }
}
```
